[tools]
selene = { source = "Kampfkarren/selene", version = "x" }
rojo = { source = "rojo-rbx/rojo", version = "x" }
remodel = { source = "rojo-rbx/remodel", version = "x" }
wally = { source = "rojo-rbx/wally", version = "x" }